##########################################
## SPRING BOOT APPLICATION
##########################################

spring.application.name=Certificates_generation
server.address=0.0.0.0
server.port=8787

#####################################################
##Load Balancing
#####################################################

server.tomcat.threads.max=800
server.tomcat.threads.min-spare=100
server.tomcat.accept-count=2000
server.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=80
spring.datasource.hikari.minimum-idle=20
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
logging.level.org.hibernate.SQL=ERROR
net.sf.jasperreports.default.pdf.embedded=false
net.sf.jasperreports.awt.ignore.missing.font=true


##########################################
##  DATABASE CONFIG (LOCAL POSTGRESQL)
##########################################

spring.datasource.url=jdbc:postgresql://localhost:5432/Genkart
spring.datasource.username=postgres
spring.datasource.password=231303
#spring.datasource.password=Genkart@123
spring.datasource.driver-class-name=org.postgresql.Driver

##########################################
## JPA / HIBERNATE
##########################################

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

##########################################
## CORS CONFIGURATION (IMPORTANT!)
##########################################

# Allow frontend to access backend
app.cors.allowed-origins=http://160.250.204.23
app.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
app.cors.allowed-headers=*
app.cors.allow-credentials=true

##########################################
## JWT CONFIG
##########################################

app.jwt.secret=TXlTdXBlclNlY3JldEtleUZvckp3dEdlbmVyYXRpb24xMjM0
app.jwt.expiration=604800000

#####################################################
## OTHER CONFIGURATIONS (keep your existing)
#####################################################

spring.web.resources.static-locations=classpath:/static/
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nagendra.p@urbanites.in
spring.mail.password=Urbanites#538
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
app.storage.base-path=C:/Users/Nagendra/Downloads/Nagendra Data/Nagendra Data/Genkart/Genkart/backend/templates
#app.storage.base-path=C:/inetpub/wwwroot/Genkart/Genkart_Bankend/templates






